# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 0b72ca6a31ce9dd657f4fadae79016650b116f1d57f09607dcdbde2d52262e96d3f20c5f9542ffd8a75a79e063cf07e32d4935e7287036076164d27be2f4af99

test:
  secret_key_base: 39fb04379ce3e6b6d280f6dcf7a62b18e5a35513757b12bac6137a85d70d3d7b4cc71422be5b90e61dac3c22c55bb401eacae68e995afdf643231d6b39139aba

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
